// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: api/proto/message.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageClient is the client API for Message service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageClient interface {
	UpdateSessionStatus(ctx context.Context, in *UpdateSessionStatusReq, opts ...grpc.CallOption) (*UpdateSessionStatusResp, error)
	FeedSessionStream(ctx context.Context, in *FeedSessionStreamReq, opts ...grpc.CallOption) (*FeedSessionStreamResp, error)
	GetSessionStatus(ctx context.Context, in *GetSessionStatusReq, opts ...grpc.CallOption) (*GetSessionStatusResp, error)
}

type messageClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageClient(cc grpc.ClientConnInterface) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) UpdateSessionStatus(ctx context.Context, in *UpdateSessionStatusReq, opts ...grpc.CallOption) (*UpdateSessionStatusResp, error) {
	out := new(UpdateSessionStatusResp)
	err := c.cc.Invoke(ctx, "/message.Message/UpdateSessionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) FeedSessionStream(ctx context.Context, in *FeedSessionStreamReq, opts ...grpc.CallOption) (*FeedSessionStreamResp, error) {
	out := new(FeedSessionStreamResp)
	err := c.cc.Invoke(ctx, "/message.Message/FeedSessionStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) GetSessionStatus(ctx context.Context, in *GetSessionStatusReq, opts ...grpc.CallOption) (*GetSessionStatusResp, error) {
	out := new(GetSessionStatusResp)
	err := c.cc.Invoke(ctx, "/message.Message/GetSessionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServer is the server API for Message service.
// All implementations should embed UnimplementedMessageServer
// for forward compatibility
type MessageServer interface {
	UpdateSessionStatus(context.Context, *UpdateSessionStatusReq) (*UpdateSessionStatusResp, error)
	FeedSessionStream(context.Context, *FeedSessionStreamReq) (*FeedSessionStreamResp, error)
	GetSessionStatus(context.Context, *GetSessionStatusReq) (*GetSessionStatusResp, error)
}

// UnimplementedMessageServer should be embedded to have forward compatible implementations.
type UnimplementedMessageServer struct {
}

func (UnimplementedMessageServer) UpdateSessionStatus(context.Context, *UpdateSessionStatusReq) (*UpdateSessionStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSessionStatus not implemented")
}
func (UnimplementedMessageServer) FeedSessionStream(context.Context, *FeedSessionStreamReq) (*FeedSessionStreamResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedSessionStream not implemented")
}
func (UnimplementedMessageServer) GetSessionStatus(context.Context, *GetSessionStatusReq) (*GetSessionStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionStatus not implemented")
}

// UnsafeMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServer will
// result in compilation errors.
type UnsafeMessageServer interface {
	mustEmbedUnimplementedMessageServer()
}

func RegisterMessageServer(s grpc.ServiceRegistrar, srv MessageServer) {
	s.RegisterService(&Message_ServiceDesc, srv)
}

func _Message_UpdateSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).UpdateSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Message/UpdateSessionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).UpdateSessionStatus(ctx, req.(*UpdateSessionStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_FeedSessionStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedSessionStreamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).FeedSessionStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Message/FeedSessionStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).FeedSessionStream(ctx, req.(*FeedSessionStreamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_GetSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Message/GetSessionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetSessionStatus(ctx, req.(*GetSessionStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Message_ServiceDesc is the grpc.ServiceDesc for Message service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Message_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.Message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateSessionStatus",
			Handler:    _Message_UpdateSessionStatus_Handler,
		},
		{
			MethodName: "FeedSessionStream",
			Handler:    _Message_FeedSessionStream_Handler,
		},
		{
			MethodName: "GetSessionStatus",
			Handler:    _Message_GetSessionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/message.proto",
}
