waiter:
    port_rpc: ":10051"

sink:

gateway:
    port_http: ":18081"

notify:
    port_http: ":9102"

depend:
    queue: "amqp://guest:guest@localhost:5672/"
    mongo_dsn: "mongodb://localhost:27017"
    redis_dsn: "localhost:6379"

store:
    # mongo: true
    # redis: true
    size_limit: 1024 # 单个消息大小上限
    max_count: 100 # 最多保留的消息数量

debug:
    biz_log_level: 6      # 0. PanicLevel; 1. FatalLevel; 2. ErrorLevel; 3. WarnLevel; 4. InfoLevel; 5. DebugLevel; 6. TraceLevel
    sql_log_level: 3      # 1. Silent ; 2. Error ; 3. Warn ; 4. Info ;
    debug_mode: true
    pprof_waiter:  ":36060"
    pprof_sink:    ":36061"
    pprof_gateway: ":36062"
    pprof_notify:  ":36063"

    slow_threshold: 200